### ISSUE TITLE
Does not process gpx whose route is less than 1km

### ISSUE THREAD

**Issue by snooppr** [flopp/GpxTrackPoster#104]
I generated different workouts. All workouts with a distance of less than **one kilometer** are skipped 
`No tracks found.`
Many workouts can be less than 1km, such as walking or swimming.

Please add support for tracks with a distance of less than 1km.

**Comment by lowtower** [comment]
Hello @snoopr,
there is an argument `--min-distance` that suits to Your question.
I guess, it defaults to 1km.
Try setting it to 0
Cheers

**Comment by snooppr** [comment]
@lowtower Thank you!  this worked for me.
