### ISSUE TITLE
Running into "No tracks found"

### ISSUE THREAD

**Issue by randmized** [flopp/GpxTrackPoster#19]
Regardless if i use a fixed or relative path as --gpx-dir or double or single quotes, i seem to rund into the No tracks found problem. Is there a certain format expected from the GPX files? Mine gets exported as:

`<gpx version="1.1" creator=" " xmlns="http://www.topografix.com/GPX/1/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
`

**Comment by joetimmerman** [comment]
Would you mind posting one of the .gpx files you're seeing this error with so we can try to replicate the issue?

Also, could you please run in verbose mode with file output (--verbose --logfile FILENAME) and upload the resulting log file here?

**Comment by randmized** [comment]
Hi, thanks.
Using the verbose it turned out that my tracks do not have a start time.
It looks like i have to export them differently. Will give that a try. Thanks for the quick response.

**Comment by joetimmerman** [comment]
As a test I tried running the gpxinfo utility from [gpxpy](https://github.com/tkrajina/gpxpy) (the repository used here to parse the GPX files) and it didn't seem to be able to read that gpx file, so we won't be able to either. I'll take a look to see if we can fail a bit more gracefully though (with verbose logging off).

**Comment by joetimmerman** [comment]
PR #21 updated error handling/logging so that problems like this will show up directly in the terminal output regardless of verbose status. This can probably be closed.
