### ISSUE TITLE
decimal separator not translated

### ISSUE THREAD

**Issue by yeKcim** [flopp/GpxTrackPoster#31]
numbers are always displayed in english way "1234.5"

Could be great if we can choose numbers display with --language. In french, for exemple, we write "1 234,5"

something like
```python
import locale
locale.setlocale(locale.LC_ALL, 'fr_FR.UTF-8')
'{0:n}'.format(1234.5)
```
?

**Comment by flopp** [comment]
You're right. 
I'll implement that...
