### ISSUE TITLE
Use tox instead of Makefile ?

### ISSUE THREAD

**Issue by Djailla** [flopp/GpxTrackPoster#32]
Hello,

Would you consider adding tox / pex support instead of Makefile ?

Regards

**Comment by flopp** [comment]
Thank you for the suggestion!
I have to look into that as I have no experience with neither tox nor pex.

**Comment by Djailla** [comment]
I can provide support and a PR so that you can have a look.

I would also work on a tool to sort Strava data exported in bulk from the
website

Le ven. 21 juin 2019 à 14:37, Florian Pigorsch <notifications@github.com> a
écrit :

**Comment by flopp** [comment]
A PR would be nice!

For reading Strava export, I have a local script that uses `gpsbabel` to convert `.fit` files into `.gpx`.

**Comment by Djailla** [comment]
Ah ! Would be great to share it too. What about tcx files ?
