### ISSUE TITLE
Add Strava Import

### ISSUE THREAD

**Issue by flopp** [flopp/GpxTrackPoster#44]
Add a Strava import function (via `stravalib`).
It may be enough to fetch the activities overview which contains the actual activity tracks as stripped down "summary polylines".

**Comment by yihong0618** [comment]
> Add a Strava import function (via `stravalib`).
> It may be enough to fetch the activities overview which contains the actual activity tracks as stripped down "summary polylines".

But I seems not contain all Gpx data can we use sqlite like https://github.com/flopp/activities

**Comment by yihong0618** [comment]
@flopp 
Can I take a pr for this？

implementation:
1. add the configuration option strava_config.py to read client_id, client_secret
2. add a description of how to get a token (I suggest a refresh token)
3. add option --from-strava to cli.py
4. special run, can use strava id
5. The cache remains the same(maybe add strava id?).
6. Read from strava without multiple processes

Do you have any suggestions?

**Comment by flopp** [comment]
Sounds great. Go ahead if you want to ...
