### ISSUE TITLE
Incorrect case of month names

### ISSUE THREAD

**Issue by sikmir** [flopp/GpxTrackPoster#50]
Month names are printed in the nominative case for all languages except Russian, where it should be `январь` instead of `января` in the example bellow, compare:
* `--language de_DE`:
![out-de](https://user-images.githubusercontent.com/688044/91774335-3eb64600-ebf1-11ea-9d94-741722dbbf32.png)
* `--language en_US`:
![out-en](https://user-images.githubusercontent.com/688044/91774339-3f4edc80-ebf1-11ea-83b3-cd500d0067df.png)
* `--language fi_FI`:
![out-fi](https://user-images.githubusercontent.com/688044/91774340-3fe77300-ebf1-11ea-8506-dba7f0fa4fce.png)
* `--language fr_FR`:
![out-fr](https://user-images.githubusercontent.com/688044/91774343-40800980-ebf1-11ea-8af6-80063b69f02c.png)
* `--language ru_RU`:
![out-ru](https://user-images.githubusercontent.com/688044/91774344-40800980-ebf1-11ea-9fe1-8f3e35715836.png)

That's caused by:
https://github.com/flopp/GpxTrackPoster/blob/2a405da9dbdb153c584beed055fd84879724a075/gpxtrackposter/calendar_drawer.py#L105
Let's check it:
```sh
$ python
>>> from datetime import datetime
>>> import locale
>>> locale.setlocale(locale.LC_ALL, 'ru_RU.UTF-8')
'ru_RU.UTF-8'
>>> datetime.today().strftime('%B')
'сентября'
```

**Comment by yihong0618** [comment]
@sikmir 

I also find something like this when translate to Chinese, for my case, I added a special case

![image](https://user-images.githubusercontent.com/15976103/91791052-bd889e80-ec44-11ea-979b-b0196db48fc7.png)

**Comment by flopp** [comment]
So, `strftime('%B')` returns a wrong string when using the `ru_RU.UTF-8` locale?

**Comment by sikmir** [comment]
> So, `strftime('%B')` returns a wrong string when using the `ru_RU.UTF-8` locale?

Yes, the reason is that `strftime` knows nothing about grammatical cases. Month name substituted by `%B` is correct in such context as `strftime('%d %B')` (`01 сентября`), but that is wrong in case of `strftime('%B')` (`сентябрь` is expected).

**Comment by flopp** [comment]
I guess, I will add a `localization.py` file with locale-aware functions that return month & day names, e.g. something like

```
def localized_month_name(locale_name: str, date: datetime.date) -> str:
    # special case for russian
    if locale_name == "ru_RU":
        return ...
    # default
    return date.strftime("%B")

def localized_day_of_week_name(locale_name: str, day_of_week: int, short: bool) -> str:
    # special case for chinese
    if locale_name == "zh_CN":
        ...
        return ...
    # default case
   ...
   return ...
```

Would that work?

**Comment by yihong0618** [comment]
I think so.

**Comment by sikmir** [comment]
What about adding util function with all month names and maintaining their proper translations for us without relying on `strftime`?

**Comment by flopp** [comment]
@sikmir for now, I've added `localization.py` with functions `localized_day_of_week_name` and `localized_month_name` that use the day/month names of the current locale by default. If a language (like Russian) requires some special treatment, the functions can be adapted accordingly; I've already done this for Chinese short day names.
You can now extend `localized_month_name` with the special cases for Russian.

**Comment by sikmir** [comment]
That treatment is not like for Chinese short day names, here we have no proper translations, so we need something like https://github.com/django/django/blob/master/django/utils/dates.py#L13-L17

**Comment by flopp** [comment]
@sikmir I've just added explicit month translations (with initial translations based on `strftime('%B')`).

I would be great if you could fix the Russian translation file (`locale/ru_RU/LC_MESSAGES/gpxposter.po`) such that the month names are correct.
