### ISSUE TITLE
Consider about time zones when Calendar poster or GitHub poster?

### ISSUE THREAD

**Issue by yihong0618** [flopp/GpxTrackPoster#54]
Consider about time zones when Calendar poster or GitHub poster?
Because we can get time zone from the GPX ( lat, lon can get the time zone)

**Comment by flopp** [comment]
Yes, why not. Is there a Python library to determine the time zone from lat/lon?

**Comment by yihong0618** [comment]
> Yes, why not. Is there a Python library to determine the time zone from lat/lon?

Yes I think there are some, let me have a try~

**Comment by yihong0618** [comment]
There are two cases
1. gpx itself with time zone
2. gpx is utc time we get the time zone by algorithm (I use this library which is faster https://github.com/MrMinimal64/timezonefinder)

-------

I think it's better to add a parameter -- use-localtime If we add this parameter (like strava), we switch the time zone for the user.
