### ISSUE TITLE
Add multilanguage support

### ISSUE THREAD

**Issue by mipapo** [flopp/GpxTrackPoster#6]
Using gettext

Generating raw *.pot file
`pygettext3 -d gpxposter src/*.py`

paramter `--language <lang_code>`
Eg. `--language de_DE

Fallback is English
Current work at: https://github.com/mipapo/GpxTrackPoster

I would prefer if "Runs" would be renamed to "Number" to have a more general naming 

If you want I can add the translation to https://translate.runalyze.com/ so that everyone can easily add new languages

**Comment by flopp** [comment]
Nice!

Using "translate.runalyze.com" for crowd-sourced translation would be nice. Of course, one could alternative service like https://crowdin.com/.

Regarding "Runs" vs "Numbers":
I think it would be preferable if the whole "statistics section" was configurable via some kind of template file. Such that every user can select which data is shown, which labels are used, and so on.

**Comment by mipapo** [comment]
@flopp Yep, but It's not free ;) You could also use the hosted weblate version (free for open-source projects -> https://weblate.org/en/hosting/#free)

A configureable statistics section would be nice

**Comment by mipapo** [comment]
@flopp  You will get a MR soon!

**Comment by mipapo** [comment]
Fixed in 3b76ac35e0cb827eb63afd3c69f99ec873d78e22
