### ISSUE TITLE
feature: heatmap years to svg layers

### ISSUE THREAD

**Issue by yeKcim** [flopp/GpxTrackPoster#70]
when drawing heatmap with several years, separate each year in layers could be great (same scale, can enable or disable easily in svg editor…)

**Comment by flopp** [comment]
I'm now putting everything into separate groups:

- The header and footer areas are but into the groups "header" and "footer".
- The main drawing area is put into the group "tracks".
- Individual years (inside the main drawing area) are put into groups "yearXXXX".

I hope this helps...
