### ISSUE TITLE
All years?

### ISSUE THREAD

**Issue by oboingo** [flopp/GpxTrackPoster#8]
Hi there, can we get an option to show all years?  Or more than one year at a time?  

I would like to combine several years at a time on the grid and heatmaps at least (might be tougher on the calendar and circular modes).

**Comment by flopp** [comment]
Currently, the script only supports exactly one year.
But you are right - a more flexible time range would be nice for the "grid" and "heatmap" variants.

**Comment by laufhannes** [comment]
At least for the heatmap it's done by commenting out the following two lines in [track_loader.py#L90-L91](https://github.com/flopp/GpxTrackPoster/blob/c4c8b283752f17dd037438e48e4e9877bbb412a4/src/track_loader.py#L90-L91):
```py
elif t.start_time.year != self.year:
    print("{}: skipping track with wrong year {}".format(file_name, t.start_time.year))
```

**Comment by flopp** [comment]
5cbd4fa32bc6fd3ea3cf2cc081c822a4b7a13beb 

New values for option `--year`:
- Display single year: `--year 2016`
- Display year range: `--year 2014-2016`
- Display all years: `--year all`
