### ISSUE TITLE
Track Loader fails for GPX tracks without a "type"

### ISSUE THREAD

**Issue by AYellowDart** [flopp/GpxTrackPoster#90]
The recent update for activity type filtering causes the import of GPX files without a "type" to fail. I am using this software to import GPX tracks from ForeFlight which have no type field in the track. Reverting to the prior commit solves the problem as does adding a type field to GPX file manually.

Thanks!

**Comment by lowtower** [comment]
@AYellowDart:
I wasn't aware of the fact that a gpx file can come without a type.
Can You test my  [PR](https://github.com/flopp/GpxTrackPoster/pull/91) with Your setting?
Thanks in advance
LT

**Comment by AYellowDart** [comment]
That did it. Works great with no editing.
I took at a look at the GPX 1.1 standard and track type is optional.
Thank you!
